[package]
name = "maw-git"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2"
gix = { version = "0.72", default-features = false, features = [
    "basic",
    "worktree-mutation",
    "index",
    "worktree-stream",
    "revision",
    "status",
    "dirwalk",
] }
gix-diff = "0.50"
gix-object = "0.48"
